name: Common Workflow

on:
  workflow_call:
    inputs:
      version: # the variable you can use in place of a matrix
        required: true
        type: string

jobs:
  build:
    name: Verify all tools are available for each PHP version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "PHP Version = " ${{ inputs.version }}
      - name: Setup PHP ${{ inputs.version }}
        uses: shivammathur/setup-php@2.25.1
        with:
          php-version: ${{ inputs.version }}